### ISSUE TITLE
Last update broke it !

### ISSUE THREAD

**Issue by nekonokamii** [duotang12/Dofus-Unity-Keyboard-Map-Changer#1]
Hello, last update of the game broke it for me and some of my friends :p

**Comment by duotang12** [comment]
Hello!

You are right, they changed the naming convention of the window. The name of the window is now the name of your character.

To fix  the problem, I suggest changing `Dofus` here to the name of your character: https://github.com/duotang12/Dofus-Unity-Keyboard-Map-Changer/blob/474d4ec5cb788f139551561ce453fd074bb67117/movement_script.ahk#L51

Hope it helps!

**Comment by duotang12** [comment]
Actually, forget what I said earlier.

I just pushed a fix for you problem. It now uses the executable name instead of the window name to check if the window is activated.

Here is the PR if you want to see: https://github.com/duotang12/Dofus-Unity-Keyboard-Map-Changer/pull/2
